// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6IfFqpOxGXj0OWvxdY7knZGdf8M-FCHE',
    appId: '1:226880405430:web:62a789824187a83101cb17',
    messagingSenderId: '226880405430',
    projectId: 'laptopharborapp-22d8d',
    authDomain: 'laptopharborapp-22d8d.firebaseapp.com',
    storageBucket: 'laptopharborapp-22d8d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH-dd6yMRQcT4OxYEte0bTbohnIKm8EdU',
    appId: '1:226880405430:android:c963295489985f4601cb17',
    messagingSenderId: '226880405430',
    projectId: 'laptopharborapp-22d8d',
    storageBucket: 'laptopharborapp-22d8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA48CtLGAzQE5f2Vr4rNEmHXlNBGYzROK0',
    appId: '1:226880405430:ios:09d14a084dc3ee7c01cb17',
    messagingSenderId: '226880405430',
    projectId: 'laptopharborapp-22d8d',
    storageBucket: 'laptopharborapp-22d8d.firebasestorage.app',
    iosBundleId: 'com.example.laptopharboApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA48CtLGAzQE5f2Vr4rNEmHXlNBGYzROK0',
    appId: '1:226880405430:ios:09d14a084dc3ee7c01cb17',
    messagingSenderId: '226880405430',
    projectId: 'laptopharborapp-22d8d',
    storageBucket: 'laptopharborapp-22d8d.firebasestorage.app',
    iosBundleId: 'com.example.laptopharboApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6IfFqpOxGXj0OWvxdY7knZGdf8M-FCHE',
    appId: '1:226880405430:web:7321e50b948a6ab301cb17',
    messagingSenderId: '226880405430',
    projectId: 'laptopharborapp-22d8d',
    authDomain: 'laptopharborapp-22d8d.firebaseapp.com',
    storageBucket: 'laptopharborapp-22d8d.firebasestorage.app',
  );
}
